chnaged ci-cd.yml file

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -160,13 +160,30 @@ jobs:
           host: ${{ vars.VM_HOST }}
           username: ${{ vars.VM_USER }}
           key: ${{ secrets.VM_SSH_KEY }}
+          # script: |
+          #   set -e
+          #   export DOCKERHUB_USERNAME='${{ vars.DOCKERHUB_USERNAME }}'
+          #   cd ${{ vars.VM_APP_PATH }}
+          #   git pull origin main || git pull origin master
+          #   docker compose -f docker-compose.hub.yml pull
+          #   # Remote prune: clean up dangling / old images (safe-ish)
+          #   docker image prune -af --filter "until=24h" || true
+          #   # Safe restart of stack
+          #   docker compose -f docker-compose.hub.yml up -d
           script: |
-            set -e
-            export DOCKERHUB_USERNAME='${{ vars.DOCKERHUB_USERNAME }}'
-            cd ${{ vars.VM_APP_PATH }}
-            git pull origin main || git pull origin master
-            docker compose -f docker-compose.hub.yml pull
-            # Remote prune: clean up dangling / old images (safe-ish)
-            docker image prune -af --filter "until=24h" || true
-            # Safe restart of stack
-            docker compose -f docker-compose.hub.yml up -d
+              set -e
+              export DOCKERHUB_USERNAME='${{ vars.DOCKERHUB_USERNAME }}'
+
+              if [ ! -d "${{ vars.VM_APP_PATH }}" ]; then
+                git clone https://github.com/${{ github.repository }} ${{ vars.VM_APP_PATH }}
+              fi
+
+              cd ${{ vars.VM_APP_PATH }}
+
+              git pull origin main || git pull origin master
+
+              docker compose -f docker-compose.hub.yml pull
+
+              docker image prune -af --filter "until=24h" || true
+
+              docker compose -f docker-compose.hub.yml up -d
